window:
  decorations: none

scrolling:
  history: 99999

font:
  size: 16
  normal:
    family: Iosevka Nerd Font
    style: Regular

  bold:
    style: Bold

  italic:
    style: Italic

  bold_italic:
    style: Bold Italic

cursor:
  vi_mode_style: Underline

shell:
  program: bash
  args:
    - -l
    - -c
    - "tmux attach || tmux"
