window:
  decorations: none

scrolling:
  history: 99999

font:
  size: 12
  normal:
    family: Iosevka Nerd Font
    style: Regular

cursor:
  vi_mode_style: Underline

shell:
  program: bash
  args:
    - -l
    - -c
    - "tmux attach || tmux"
